stages:
  - build
  - codestyle
  - integration_tests
  - deploy
  - notify

building:
  stage: build
  script:
    - cd src/cat/
    - make s21_cat
    - cd ../grep
    - make s21_grep
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 day

style: 
   stage: codestyle
   script:
     - cp materials/linters/.clang-format src/cat
     - cp materials/linters/.clang-format src/grep
     - cd src/cat
     - clang-format -n --Werror *.c
     - cd ../grep
     - clang-format -n --Werror *.c

testing:
  stage: integration_tests
  script: 
     - cd src/cat
     - bash test_func_cat.sh
#     - cd ../grep
#     - bash test_func_grep.sh

ci_success:
  stage: notify
  needs:
    - building
    - style
    - testing
  script:
    - cd src
    - sh notify_bot.sh "CI Success"

deploying:
  stage: deploy
  when: manual
  allow_failure: false
  script:
    - cd src
    - chmod +x deploy.sh
    - bash deploy.sh 

cd_failure:
  stage: notify
  when: on_failure
  needs:
    - deploying
  script:
    - cd src
    - sh notify_bot.sh "CD Failure"

cd_success:
  stage: notify
  when: on_success
  needs:
    - deploying
  script:
    - cd src
    - sh notify_bot.sh "CD Success"

ci_failure_build:
  stage: notify
  when: on_failure
  needs: 
    - building
  script:
    - cd src
    - sh notify_bot.sh "CI build failure"

ci_failure_style:
  stage: notify
  when: on_failure
  needs:
    - style
  script:
    - cd src
    - sh notify_bot.sh "CI style test failure"

ci_failure_integration_tests:
  stage: notify
  when: on_failure
  needs:
    - testing
  script:
    - cd src
    - sh notify_bot.sh "CI integration tests failure"
